-- Load files
require('jake.plugins')
require('jake.options')
require('jake.keymaps')
require('jake.nvim-tree')
require('jake.colorscheme')
require('jake.lualine')
require('jake.cmp')
require('jake.lsp')
require('jake.telescope')
require('jake.treesitter')
require('jake.autopairs')
require('jake.comment')
require('jake.gitsigns')
