-- Load files
require('user.plugins')
require('user.options')
require('user.keymaps')
require('user.nvim-tree')
require('user.colorscheme')
require('user.lualine')
require('user.cmp')
require('user.lsp')
require('user.telescope')
require('user.treesitter')
require('user.autopairs')
require('user.comment')
require('user.gitsigns')
